[versions]
gradlePlugin = "8.5.2"
kotlin = "2.1.0"
kotlinKsp = "2.1.0-1.0.29"
kotlinCoroutines = "1.10.1"
ktlint = "11.6.1"

androidxCore = "1.13.1"
androidxAppcompat = "1.7.0"
androidxAppStartup = "1.2.0"
androidxConstraintLayout = "2.2.0"
androidxDatastore = "1.1.2"
androidxFragment = "1.8.5"
androidxNavigation = "2.8.5"
androidxRoom = "2.6.1"
androidxWorkManager = "2.9.1"
androidxHiltWorkManager = "1.2.0"
androidxJankStats = "1.0.0-beta01"
androidxSplash = "1.0.1"

gson = "2.12.1"
hilt = "2.55"
javax-inject = "1"
material = "1.12.0"

glide = "4.16.0"
timber = "5.0.1"

junit = "4.13.2"
testJunit = "1.2.1"
testEspresso = "3.6.1"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-app-compat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-app-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidxAppStartup" }
androidx-constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastore" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkManager" }
androidx-hilt-workmanager = { module = "androidx.hilt:hilt-work", version.ref = "androidxHiltWorkManager" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHiltWorkManager" }
androidx-jank-stats = { module = "androidx.metrics:metrics-performance", version.ref = "androidxJankStats" }
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplash" }

kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject"}
material = { module = "com.google.android.material:material", version.ref = "material" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "testJunit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "testEspresso" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "testEspresso" }
androidx-navigation-test = { module = "androidx.navigation:navigation-testing", version.ref = "androidxNavigation" }
androidx-room-test = { module = "androidx.room:room-testing", version.ref = "androidxRoom" }
androidx-workmanager-test = { module = "androidx.work:work-testing", version.ref = "androidxWorkManager" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }